### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by guumaster** [guumaster/hostctl#45]
The current state of the CLI and module is kind of beta(ish), is subject to small/big changes as I or the community finds it uses, requests features and I learn better ways of implementing the CLI with `cobra`.

Here are things that should be finished before reaching an stable version tag `v1.0.0`:

* [x] Add a decent amount code coverage of all files in `pkg` directory. #48
* [x] Refactor `pkg` code to expose a better API to use as module. #48
* [x] Change semantics to have profiles as arguments instead of flag. #37 #48
* [x] Allow to manage multiple profiles at once. Ex: `hostctl disable profile1 profile2... ` #48
* [x] Add mutex to save file to avoid concurrency issues. #48

**NOTE**: The issue is locked just to keep better track of the features that would be added. In anyways this mean you can't participate on deciding new features. 
I encourage you to [open new issues](https://github.com/guumaster/hostctl/issues/new?labels=feature&template=feature_request.md) with any idea you have.
